import type { EventItem } from "./types";

export const events: EventItem[] = [
  {
    id: "evt_001",
    title: "WHV Sydney Rooftop Meet-up — Cliff Dive",
    source: "humanitix",
    city: "Sydney",
    venue: "Cliff Dive, Surry Hills",
    startsAt: "2026-05-26T19:00:00Z",
    price: "Free entry · cash bar",
    cover: { gradient: ["#FB7185", "#F59E0B"], emoji: "🌇" },
    hostName: "Sofia & Sydney WHV crew",
    hostSeed: "sofia-ricci-it",
    blurb: "Monthly rooftop meet-up for new arrivals. Bring a friend, swap city tips, find your next flatmate.",
    attendees: 142,
    tags: ["meet-up", "rooftop", "free"],
  },
  {
    id: "evt_002",
    title: "Tax 101 for WHV holders — Free Webinar",
    source: "luma",
    city: "Sydney",
    venue: "Online (Zoom)",
    startsAt: "2026-05-28T18:00:00Z",
    price: "Free",
    cover: { gradient: ["#16A34A", "#14B8A6"], emoji: "🧾" },
    hostName: "Greythorn Tax",
    hostSeed: "greythorn-tax",
    blurb: "30-minute workshop covering TFN, 15% WHV tax rate, deductions, and the DASP super refund.",
    attendees: 89,
    tags: ["webinar", "tax", "online"],
  },
  {
    id: "evt_003",
    title: "Bondi Sunrise Surf — beginners welcome",
    source: "in-app",
    city: "Sydney",
    venue: "South Bondi · Meet at the lifeguard tower",
    startsAt: "2026-05-27T06:00:00Z",
    price: "$15 (board hire)",
    cover: { gradient: ["#0EA5E9", "#14B8A6"], emoji: "🏄" },
    hostName: "WHV Surf Crew",
    hostSeed: "whv-surf-crew",
    blurb: "Beginner-friendly surf lesson with a Bondi local. Boards available to hire on the beach.",
    attendees: 24,
    tags: ["surf", "bondi", "morning"],
  },
  {
    id: "evt_004",
    title: "Migration AMA — second-year visa Q&A",
    source: "humanitix",
    city: "Melbourne",
    venue: "Online + in-person, Carlton",
    startsAt: "2026-05-30T11:00:00Z",
    price: "Free",
    cover: { gradient: ["#8B5CF6", "#6366F1"], emoji: "✈️" },
    hostName: "Visa Envoy",
    hostSeed: "visa-envoy",
    blurb: "MARA-registered agents walk through the 88-day specified-work requirement and answer everything.",
    attendees: 211,
    tags: ["migration", "second-year", "AMA"],
  },
  {
    id: "evt_005",
    title: "Newtown Live Music Crawl",
    source: "eventbrite",
    city: "Sydney",
    venue: "King Street, Newtown",
    startsAt: "2026-06-01T19:30:00Z",
    price: "$25 incl. 3 venues",
    cover: { gradient: ["#FB7185", "#F43F5E"], emoji: "🎸" },
    hostName: "Sydney Backpackers Crew",
    hostSeed: "sydney-bp-crew",
    blurb: "3 venues, 3 bands, $25. Doors open at 7:30, meet at the Bank Hotel pre-show.",
    attendees: 56,
    tags: ["music", "newtown", "evening"],
  },
  {
    id: "evt_006",
    title: "Cairns reef job-fair — meet farm employers",
    source: "humanitix",
    city: "Cairns",
    venue: "Gilligan's Backpackers, Cairns",
    startsAt: "2026-06-04T10:00:00Z",
    price: "Free",
    cover: { gradient: ["#10B981", "#14B8A6"], emoji: "🌴" },
    hostName: "Cairns WHV Hub",
    hostSeed: "cairns-whv-hub",
    blurb: "10 verified employers, 50+ open roles for citrus, banana, hospitality. Bring your passport.",
    attendees: 178,
    tags: ["job-fair", "regional", "QLD"],
  },
  {
    id: "evt_007",
    title: "Free city walk — Sydney Harbour history",
    source: "luma",
    city: "Sydney",
    venue: "Circular Quay · Meet at the Cadman's Cottage",
    startsAt: "2026-05-29T10:30:00Z",
    price: "Free · tips welcome",
    cover: { gradient: ["#2563EB", "#0EA5E9"], emoji: "🚶"  },
    hostName: "Sydney Free Tours",
    hostSeed: "sydney-free-tours",
    blurb: "2-hour walking tour of Sydney's harbour history. Tip-based, perfect for the first weekend.",
    attendees: 67,
    tags: ["tour", "free", "weekend"],
  },
  {
    id: "evt_008",
    title: "Migration help-desk — drop-in, Melbourne CBD",
    source: "in-app",
    city: "Melbourne",
    venue: "Melbourne Central Library",
    startsAt: "2026-06-05T13:00:00Z",
    price: "Free",
    cover: { gradient: ["#F97316", "#FB7185"], emoji: "📑" },
    hostName: "Visa Envoy",
    hostSeed: "visa-envoy",
    blurb: "15-minute one-on-one consultations with MARA-registered agents. Bring your work logbook.",
    attendees: 32,
    tags: ["help-desk", "migration"],
  },
];
