import type { JobItem } from "./types";

export const jobs: JobItem[] = [
  {
    id: "p3j_001",
    role: "Café floor — Surry Hills",
    company: "Single O Surry Hills",
    industry: "Hospitality",
    city: "Sydney",
    state: "NSW",
    payRate: "$32/hr + tips",
    startDate: "2026-06-02",
    endDate: "Ongoing",
    visa: ["417", "462"],
    accommodationProvided: false,
    blurb: "Award-winning specialty coffee bar in Surry Hills. Looking for an all-rounder with prior FOH or barista experience.",
    whvOnly: false,
    postedAt: "2026-05-24",
  },
  {
    id: "p3j_002",
    role: "Mandarin pickers — Crew of 12",
    company: "Riverina Citrus",
    industry: "Horticulture",
    city: "Sydney",
    state: "NSW",
    payRate: "$0.38/piece · award floor",
    startDate: "2026-06-08",
    endDate: "2026-08-30",
    visa: ["417", "462"],
    accommodationProvided: true,
    blurb: "Mandarin picking, on-orchard bunkhouse provided. Repeat WHV crews preferred. Counts toward 88 days.",
    whvOnly: true,
    postedAt: "2026-05-02",
  },
  {
    id: "p3j_003",
    role: "Lodge F&B service",
    company: "Cape Reef Lodge",
    industry: "Hospitality",
    city: "Cairns",
    state: "QLD",
    payRate: "$31.20/hr",
    startDate: "2026-06-15",
    endDate: "2026-11-30",
    visa: ["417", "462"],
    accommodationProvided: true,
    blurb: "Boutique reef lodge, 64 rooms. Staff accommodation on-site. RSA preferred (we'll fast-track if you don't have one).",
    whvOnly: true,
    postedAt: "2026-04-28",
  },
  {
    id: "p3j_004",
    role: "Bartender weekends — Melbourne",
    company: "Black Pearl Bar",
    industry: "Hospitality",
    city: "Melbourne",
    state: "VIC",
    payRate: "$36/hr Sat-Sun",
    startDate: "2026-05-30",
    endDate: "Ongoing",
    visa: ["417", "462"],
    accommodationProvided: false,
    blurb: "Cult-favourite Fitzroy cocktail bar. RSA required. We'll teach you the rest.",
    whvOnly: false,
    postedAt: "2026-05-21",
  },
  {
    id: "p3j_005",
    role: "Hostel reception — Bondi",
    company: "Wake Up! Bondi",
    industry: "Hospitality",
    city: "Sydney",
    state: "NSW",
    payRate: "$28/hr + free bed",
    startDate: "2026-06-10",
    endDate: "2026-09-30",
    visa: ["417", "462"],
    accommodationProvided: true,
    blurb: "Reception at Bondi's busiest backpacker hostel. Trade ~3 shifts/week for a free dorm bed.",
    whvOnly: true,
    postedAt: "2026-05-20",
  },
  {
    id: "p3j_006",
    role: "Margaret River cellar hands",
    company: "Margaret River Wine Estates",
    industry: "Horticulture",
    city: "Perth",
    state: "WA",
    payRate: "$32/hr",
    startDate: "2026-07-01",
    endDate: "2026-10-15",
    visa: ["417", "462"],
    accommodationProvided: false,
    blurb: "Cellar hands for vintage across 4 boutique wineries. Experience preferred, training available.",
    whvOnly: true,
    postedAt: "2026-05-12",
  },
  {
    id: "p3j_007",
    role: "Strawberry pickers — Wamuran",
    company: "Outback Recruitment Partners",
    industry: "Horticulture",
    city: "Brisbane",
    state: "QLD",
    payRate: "$0.32/piece + bonus",
    startDate: "2026-06-05",
    endDate: "2026-10-20",
    visa: ["417", "462"],
    accommodationProvided: true,
    blurb: "High-volume strawberry pick. Bunkhouse + shuttle bus included. Repeat crews qualify for bonus.",
    whvOnly: true,
    postedAt: "2026-04-22",
  },
  {
    id: "p3j_008",
    role: "Kitchen hand — Newtown",
    company: "Mary's Newtown",
    industry: "Hospitality",
    city: "Sydney",
    state: "NSW",
    payRate: "$29/hr",
    startDate: "2026-06-01",
    endDate: "Ongoing",
    visa: ["417", "462"],
    accommodationProvided: false,
    blurb: "Iconic burger joint. Looking for 2 kitchen hands, evening shifts. Fast-paced, lots of teamwork.",
    whvOnly: false,
    postedAt: "2026-05-22",
  },
];
