import type { ServiceTile, ServiceCategory } from "./types";

// All 10 home-grid tiles, in the order specified by Draft App.xlsx.
export const tiles: ServiceTile[] = [
  // Row 1
  {
    slug: "community",
    label: "Community",
    shortDesc: "Chat with WHV holders near you",
    iconKey: "MessagesSquare",
    accent: "brand",
    inApp: true,
  },
  {
    slug: "events",
    label: "Events",
    shortDesc: "Meet-ups, parties, free walks",
    iconKey: "PartyPopper",
    accent: "coral",
    inApp: true,
  },
  {
    slug: "jobs",
    label: "Jobs",
    shortDesc: "Roles from verified employers",
    iconKey: "Briefcase",
    accent: "mint",
    inApp: true,
  },
  {
    slug: "certification",
    label: "Certification",
    shortDesc: "RSA, white card, food safety",
    iconKey: "BadgeCheck",
    accent: "amber",
    inApp: false,
  },
  {
    slug: "bank-setup",
    label: "Bank Setup",
    shortDesc: "Open an Aussie bank account",
    iconKey: "Landmark",
    accent: "indigo",
    inApp: false,
  },
  // Row 2
  {
    slug: "tax-agents",
    label: "Tax Agents",
    shortDesc: "TFN + WHV tax returns",
    iconKey: "Calculator",
    accent: "emerald",
    inApp: false,
  },
  {
    slug: "insurance",
    label: "Insurance",
    shortDesc: "Health, travel & OVHC plans",
    iconKey: "ShieldCheck",
    accent: "sky",
    inApp: false,
  },
  {
    slug: "migration",
    label: "Migration",
    shortDesc: "Second-year, 88 days, agents",
    iconKey: "Plane",
    accent: "violet",
    inApp: false,
  },
  {
    slug: "accommodation",
    label: "Accommodation",
    shortDesc: "Hostels, share-houses, stays",
    iconKey: "Home",
    accent: "orange",
    inApp: false,
  },
  {
    slug: "support",
    label: "Support",
    shortDesc: "24/7 help, embassies, safety",
    iconKey: "LifeBuoy",
    accent: "rose",
    inApp: false,
  },
];

// Reusable content for the 7 directory-style service pages.
// (community, events, jobs are deep dives — not here.)
export const serviceCategories: Record<string, ServiceCategory> = {
  certification: {
    slug: "certification",
    label: "Certification",
    iconKey: "BadgeCheck",
    heroAccent: "amber",
    intro: "Get the certs Aussie employers actually ask for.",
    longDesc:
      "Most hospitality and front-of-house jobs in Australia require state-specific certifications. Knock them out online in a few hours.",
    checklist: [
      { label: "RSA (Responsible Service of Alcohol) — required for bars & many cafes", done: false },
      { label: "Food Safety Supervisor (NSW/QLD/VIC) — required by venue", done: false },
      { label: "White Card — required on all construction sites", done: false },
      { label: "RSG / RCG (gaming) — only if you'll work venues with pokies", done: false },
    ],
    providers: [
      {
        id: "cert_001",
        name: "Express Online Learning",
        blurb: "RSA + RCG + Food Safety, all states covered, ~$45–95 each. Same-day certificate to your email.",
        rating: 4.7,
        reviewCount: 8421,
        whvFriendly: true,
        highlights: ["All states", "Same-day cert", "~3 hours online"],
        startingPrice: "$45",
        ctaLabel: "Start with Express",
      },
      {
        id: "cert_002",
        name: "AHA NSW Training",
        blurb: "Hospitality association — recognised by every Sydney venue. Slightly pricier, gold-standard certs.",
        rating: 4.6,
        reviewCount: 2103,
        highlights: ["NSW gold standard", "Industry-backed"],
        startingPrice: "$120",
        ctaLabel: "Browse AHA courses",
      },
      {
        id: "cert_003",
        name: "Allens Training (White Card)",
        blurb: "Nationally-recognised construction White Card. Required before stepping foot on any site.",
        rating: 4.5,
        reviewCount: 5610,
        whvFriendly: true,
        highlights: ["National", "Online & in-person"],
        startingPrice: "$60",
        ctaLabel: "Get White Card",
      },
    ],
    faq: [
      {
        q: "Do I need RSA before applying for hospo jobs?",
        a: "Not before applying, but you can't start a shift without one in NSW/QLD/VIC. Most hires get it in the week between offer and start.",
      },
      {
        q: "Is the RSA the same across states?",
        a: "No — each state has its own RSA. Confirm with the venue which state's certificate they need.",
      },
    ],
  },

  "bank-setup": {
    slug: "bank-setup",
    label: "Bank Setup",
    iconKey: "Landmark",
    heroAccent: "indigo",
    intro: "Open a free Aussie account before you arrive, so your first paycheque has somewhere to land.",
    longDesc:
      "Most of the Big Four banks let you start an application online from overseas and finish it in a branch with your passport once you arrive. No fees while you're a WHV holder.",
    checklist: [
      { label: "Open the account online before you arrive", done: true },
      { label: "Bring passport + Aussie address to the branch", done: false },
      { label: "Get a debit card linked to a tap-to-pay app", done: false },
      { label: "Set up Osko / PayID for instant transfers", done: false },
    ],
    providers: [
      {
        id: "bank_001",
        name: "CommBank — Smart Access (WHV)",
        blurb: "Australia's biggest bank. Strong app, NetBank, branch on every corner. No monthly fee for WHV holders.",
        rating: 4.3,
        reviewCount: 28430,
        whvFriendly: true,
        highlights: ["Pre-arrival sign-up", "Free for WHV", "Biggest ATM network"],
        ctaLabel: "Start CommBank app",
      },
      {
        id: "bank_002",
        name: "ANZ Plus",
        blurb: "Brand-new app-first bank from ANZ. Round-up savings, no fees, instant card in Apple/Google Pay.",
        rating: 4.5,
        reviewCount: 4120,
        whvFriendly: true,
        highlights: ["App-first", "Instant virtual card", "Round-up savings"],
        ctaLabel: "Open ANZ Plus",
      },
      {
        id: "bank_003",
        name: "Westpac Choice",
        blurb: "Pre-arrival sign-up, fee-free as long as you deposit $2k/mth. Popular with backpackers in QLD.",
        rating: 4.1,
        reviewCount: 11402,
        whvFriendly: true,
        highlights: ["Pre-arrival sign-up", "Strong QLD presence"],
        ctaLabel: "Open Westpac account",
      },
      {
        id: "bank_004",
        name: "Wise Multi-currency",
        blurb: "Not an Aussie bank but holds AUD, EUR, GBP, USD. Great if you'll work across borders.",
        rating: 4.7,
        reviewCount: 60210,
        highlights: ["Multi-currency", "Cheap transfers home"],
        ctaLabel: "Add Wise account",
      },
    ],
    faq: [
      {
        q: "Can I open an account before I arrive in Australia?",
        a: "Yes — CommBank, ANZ, Westpac and NAB all let you start online. You finalise it in a branch with your passport when you land.",
      },
      {
        q: "Will I be charged monthly fees?",
        a: "Most accounts are free for under-30s or WHV holders. Always confirm before signing — fees creep back at 30 or 31.",
      },
    ],
  },

  "tax-agents": {
    slug: "tax-agents",
    label: "Tax Agents",
    iconKey: "Calculator",
    heroAccent: "emerald",
    intro: "WHV tax is its own ecosystem. Don't DIY it your first year.",
    longDesc:
      "As a WHV holder, you're taxed at 15% on income up to $45k and most agents can get you a few hundred dollars back from rebates and deductions. The good ones know what's WHV-specific.",
    checklist: [
      { label: "Apply for a Tax File Number (TFN) — free, online via ATO", done: false },
      { label: "Give your TFN to your employer in the first 28 days", done: false },
      { label: "Lodge your tax return between July and October", done: false },
      { label: "Claim any super back when you leave Australia", done: false },
    ],
    providers: [
      {
        id: "tax_001",
        name: "Greythorn Tax",
        blurb: "Backpacker-tax specialists since 2010. They know every WHV deduction. ~$120 flat, refund usually 5–7 days.",
        rating: 4.8,
        reviewCount: 12030,
        whvFriendly: true,
        highlights: ["WHV-only specialists", "Refund in 5–7 days", "Online chat support"],
        startingPrice: "$120 flat",
        ctaLabel: "Lodge with Greythorn",
      },
      {
        id: "tax_002",
        name: "H&R Block — WHV",
        blurb: "National chain, branches in every city. More expensive but face-to-face if you prefer that.",
        rating: 4.4,
        reviewCount: 8901,
        whvFriendly: true,
        highlights: ["In-person", "Walk-in branches"],
        startingPrice: "$165",
        ctaLabel: "Book at H&R Block",
      },
      {
        id: "tax_003",
        name: "Taxback.com",
        blurb: "International tax-back specialist. Particularly strong if you want to claim super refund when you leave.",
        rating: 4.3,
        reviewCount: 22301,
        whvFriendly: true,
        highlights: ["Departing Australia super refund", "Multi-country"],
        ctaLabel: "Use Taxback.com",
      },
    ],
    faq: [
      {
        q: "Do I really need a tax agent?",
        a: "Not strictly — myTax (the ATO portal) works for simple cases. But WHV taxation has its own rules and most first-timers leave money on the table by DIY-ing.",
      },
      {
        q: "Can I get my super back when I leave?",
        a: "Yes, via a DASP (Departing Australia Superannuation Payment) claim. Tax agents typically handle this for ~$150–250.",
      },
    ],
  },

  insurance: {
    slug: "insurance",
    label: "Insurance",
    iconKey: "ShieldCheck",
    heroAccent: "sky",
    intro: "Medicare doesn't cover WHV holders. Pick one of these before your first surf wipe-out.",
    longDesc:
      "Public Medicare is only available to 417/462 holders from a handful of reciprocal-agreement countries. Most WHVers need OVHC (Overseas Visitor Health Cover) plus travel insurance.",
    checklist: [
      { label: "Check if your country has a reciprocal Medicare agreement", done: false },
      { label: "Choose OVHC if your country isn't on the list", done: false },
      { label: "Travel insurance for gear, cancellations, adventure activities", done: false },
      { label: "Carry your policy number in your phone wallet", done: false },
    ],
    providers: [
      {
        id: "ins_001",
        name: "Bupa — Working Visa Health Cover",
        blurb: "Largest OVHC provider. Strong network of partner GPs. From $90/mth for basic.",
        rating: 4.4,
        reviewCount: 9120,
        whvFriendly: true,
        highlights: ["OVHC", "Direct billing with most GPs"],
        startingPrice: "$90/mth",
        ctaLabel: "Quote with Bupa",
      },
      {
        id: "ins_002",
        name: "Medibank OSHC + OVHC",
        blurb: "Big-brand insurer with backpacker-tuned OVHC plans. Often bundled with travel insurance.",
        rating: 4.3,
        reviewCount: 7820,
        whvFriendly: true,
        highlights: ["Bundled travel cover", "Large hospital network"],
        startingPrice: "$95/mth",
        ctaLabel: "Quote with Medibank",
      },
      {
        id: "ins_003",
        name: "Cover-More Working Holiday",
        blurb: "Travel-insurance specialist. Stronger on adventure activities (surf, hike, dive) than pure OVHC.",
        rating: 4.6,
        reviewCount: 4012,
        highlights: ["Adventure cover", "Trip cancellation"],
        startingPrice: "$8/day",
        ctaLabel: "Get a Cover-More quote",
      },
    ],
    faq: [
      {
        q: "Is OVHC required for a WHV?",
        a: "Recommended, not strictly required. But a single ER visit without it can cost AUD $3,000+.",
      },
      {
        q: "Can I use Medicare?",
        a: "Only if your home country has a Reciprocal Health Care Agreement with Australia (UK, Italy, NZ, NL, Ireland, Belgium, Sweden, Finland, Norway, Malta, Slovenia).",
      },
    ],
  },

  migration: {
    slug: "migration",
    label: "Migration",
    iconKey: "Plane",
    heroAccent: "violet",
    intro: "Second-year visa, 88 days of specified work, and the agents worth paying for.",
    longDesc:
      "WHV second- and third-year extensions exist if you complete specified regional work. Migration agents are pricey but the rules change often — pay for advice if you're unsure.",
    checklist: [
      { label: "Track your 88 days of specified work in writing", done: false },
      { label: "Get payslips and a postcode-verified letter from each employer", done: false },
      { label: "Apply for 2nd-year before your current visa expires", done: false },
      { label: "Use only MARA-registered agents (they have a numbered ID)", done: false },
    ],
    providers: [
      {
        id: "mig_001",
        name: "Visa Envoy — WHV Specialists",
        blurb: "MARA-registered. Specialise in 2nd and 3rd-year applications. Flat-fee, no surprises.",
        rating: 4.7,
        reviewCount: 3120,
        whvFriendly: true,
        highlights: ["MARA #0001234", "Flat fee", "2nd/3rd year only"],
        startingPrice: "$650",
        ctaLabel: "Book with Visa Envoy",
      },
      {
        id: "mig_002",
        name: "Australia Wide Migration",
        blurb: "Multi-purpose agency — handles 482/186 sponsorship if you want to stay long-term after WHV.",
        rating: 4.5,
        reviewCount: 1820,
        highlights: ["Path to permanent", "MARA registered"],
        startingPrice: "$1,200",
        ctaLabel: "Book consultation",
      },
      {
        id: "mig_003",
        name: "Department of Home Affairs (DIY)",
        blurb: "Official government portal. Free, but you do all the paperwork yourself.",
        rating: 3.6,
        reviewCount: 0,
        highlights: ["Official", "Free", "DIY"],
        ctaLabel: "Open ImmiAccount",
      },
    ],
    faq: [
      {
        q: "What counts as ‘specified work' for the 88 days?",
        a: "Plant or animal cultivation, fishing/pearling, tree farming, mining, construction in specified postcodes. Tourism/hospitality counts for 462s in certain regions only.",
      },
      {
        q: "Do I need a migration agent?",
        a: "Not legally, but the application is dense. Spend money on one if your case is borderline (e.g. work was unpaid, postcode unclear, dates close to expiry).",
      },
    ],
  },

  accommodation: {
    slug: "accommodation",
    label: "Accommodation",
    iconKey: "Home",
    heroAccent: "orange",
    intro: "Hostels for week 1, share-houses by week 2, your own room by month 3.",
    longDesc:
      "Where you stay determines a lot of your social life. Most WHVers do a week in a hostel, then a 1-3 month share-house from Flatmates or Facebook groups, then upgrade once they find work.",
    checklist: [
      { label: "Book first 5–7 nights in a backpacker-friendly hostel", done: true },
      { label: "Open a Flatmates.com.au account, complete a profile", done: false },
      { label: "Tour 3 share-houses before committing", done: false },
      { label: "Never wire bond money before a viewing", done: false },
    ],
    providers: [
      {
        id: "acc_001",
        name: "Wake Up! Hostels",
        blurb: "Three locations in Sydney, Melbourne, Bondi. Best on-site job-board and meet-up nights.",
        rating: 4.5,
        reviewCount: 12200,
        whvFriendly: true,
        highlights: ["WHV community", "Job board", "Sydney + Melbourne + Bondi"],
        startingPrice: "$48/night",
        ctaLabel: "Book Wake Up!",
      },
      {
        id: "acc_002",
        name: "Flatmates.com.au",
        blurb: "Australia's largest share-house platform. Free to browse, verified profiles.",
        rating: 4.3,
        reviewCount: 38120,
        whvFriendly: true,
        highlights: ["Largest in AU", "Verified profiles"],
        ctaLabel: "Browse Flatmates",
      },
      {
        id: "acc_003",
        name: "Nomads Backpackers",
        blurb: "East-coast hostel chain. Good for long-term backpacker stays at weekly rates.",
        rating: 4.2,
        reviewCount: 8210,
        whvFriendly: true,
        highlights: ["Weekly rates", "East-coast network"],
        startingPrice: "$220/week",
        ctaLabel: "Book Nomads",
      },
      {
        id: "acc_004",
        name: "NRMA Holiday Parks",
        blurb: "Camp + cabin + powered-site network. Great if you have a van or want a country escape.",
        rating: 4.6,
        reviewCount: 14210,
        highlights: ["Van life", "Regional locations"],
        ctaLabel: "Find a park",
      },
    ],
    faq: [
      {
        q: "Should I lock in a share-house before I arrive?",
        a: "No — always view in person. Spend your first week in a hostel and see places after work.",
      },
      {
        q: "What's a typical bond?",
        a: "Usually 2 weeks' rent. Legally must be lodged with the state's residential tenancies authority within 10 days.",
      },
    ],
  },

  support: {
    slug: "support",
    label: "Support",
    iconKey: "LifeBuoy",
    heroAccent: "rose",
    intro: "Save these numbers in your phone today.",
    longDesc:
      "Australia is generally safe, but knowing the right number to call (or service to message) when something goes wrong is the difference between a stressful afternoon and a full-blown crisis.",
    checklist: [
      { label: "Save 000 — Police / Fire / Ambulance — as a phone shortcut", done: true },
      { label: "Save 13 11 14 — Lifeline mental-health support", done: false },
      { label: "Know your embassy's after-hours emergency line", done: false },
      { label: "Know Fair Work Ombudsman if you're being underpaid", done: false },
    ],
    providers: [
      {
        id: "sup_001",
        name: "Lifeline (24/7)",
        blurb: "Free, confidential mental-health support. Phone, chat, or text. Multi-language available.",
        rating: 5,
        reviewCount: 0,
        whvFriendly: true,
        highlights: ["24/7", "Free", "Multi-language"],
        ctaLabel: "Call 13 11 14",
      },
      {
        id: "sup_002",
        name: "Fair Work Ombudsman",
        blurb: "If you suspect underpayment, wage theft, or unsafe work — they investigate for free.",
        rating: 4.7,
        reviewCount: 0,
        whvFriendly: true,
        highlights: ["Free", "Confidential", "WHV-aware"],
        ctaLabel: "Lodge a complaint",
      },
      {
        id: "sup_003",
        name: "Translating & Interpreting Service",
        blurb: "Free phone interpreters in 160+ languages, 24/7. Use it for medical or legal calls.",
        rating: 4.6,
        reviewCount: 0,
        whvFriendly: true,
        highlights: ["Free", "160+ languages"],
        ctaLabel: "Call 131 450",
      },
      {
        id: "sup_004",
        name: "ID Care",
        blurb: "If you're scammed, your passport is lost, or identity is compromised — they help you recover.",
        rating: 4.5,
        reviewCount: 1210,
        highlights: ["Scam recovery", "ID theft"],
        ctaLabel: "Call ID Care",
      },
    ],
    faq: [
      {
        q: "What's the emergency number?",
        a: "000 from any phone. The operator will route you to Police, Fire, or Ambulance.",
      },
      {
        q: "I'm being underpaid — what now?",
        a: "Document your hours and payslips, then contact the Fair Work Ombudsman. Initial advice is free and confidential.",
      },
    ],
  },
};

export const serviceSlugs = Object.keys(serviceCategories);
